using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyProductAttribute("Ninject: Dependency Injector for .NET")]
[assembly: AssemblyCompanyAttribute("Enkari, Ltd. and contributors")]
[assembly: AssemblyCopyrightAttribute("Copyright ©2007-2010, Enkari, Ltd. and contributors")]
[assembly: AssemblyVersionAttribute("1.5.0.0")]
[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]

